export const SET_MAIN_INFO = 'SET_MAIN_INFO';
export const ADD_QUESTION_FORM = 'ADD_QUESTION_FORM';
export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
export const SET_QUESTIONS = 'SET_QUESTIONS';
